name: upset-altair-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7
  - jupyter
  - nb_conda
  - pandas
  - requests
  - numpy
  - altair=4.0.0
  - jsonschema<=4.0
  - altair_saver
  - vega_datasets
